# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-20 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180613_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'ordering': ['-add_time'], 'verbose_name': '课程评论', 'verbose_name_plural': '课程评论'},
        ),
    ]
