# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-17 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='http://zhongminyong.tech', max_length=200, verbose_name='访问地址'),
        ),
    ]
