# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-22 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180617_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.FileField(default='', upload_to='teacher/%Y/%m', verbose_name='视频'),
        ),
    ]
