# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-07-09 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
            },
            bases=('courses.course',),
        ),
    ]
